[package]
name = "ami"
version = "0.1.0"
edition = "2021"

[[example]]
name = "toy"

[dependencies]
itertools = "0.14.0"
unicode-segmentation = "1.11.0"

[dev-dependencies]
ami_derive = { path = '../ami_derive' }